DROP TABLE IF EXISTS "transactions";
DROP TABLE IF EXISTS "profiles";
DROP TABLE IF EXISTS "accounts";
DROP TABLE IF EXISTS "categories";
DROP TABLE IF EXISTS "workspaces";
DROP TABLE IF EXISTS "users";
