// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package model

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                   uuid.UUID        `json:"id"`
	Name                 string           `json:"name"`
	Description          pgtype.Text      `json:"description"`
	Balance              pgtype.Numeric   `json:"balance"`
	FinancialInstitution pgtype.Text      `json:"financial_institution"`
	AccountType          pgtype.Text      `json:"account_type"`
	UserID               uuid.UUID        `json:"user_id"`
	WorkspaceID          uuid.UUID        `json:"workspace_id"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	DeletedAt            pgtype.Timestamp `json:"deleted_at"`
}

type Category struct {
	ID          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CType       string           `json:"c_type"`
	UserID      uuid.UUID        `json:"user_id"`
	WorkspaceID uuid.UUID        `json:"workspace_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}

type Profile struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Currency  string           `json:"currency"`
	Language  string           `json:"language"`
	UserID    uuid.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}

type Transaction struct {
	ID          uuid.UUID        `json:"id"`
	Title       string           `json:"title"`
	Note        pgtype.Text      `json:"note"`
	Currency    pgtype.Text      `json:"currency"`
	Value       pgtype.Numeric   `json:"value"`
	UserID      uuid.UUID        `json:"user_id"`
	WorkspaceID uuid.UUID        `json:"workspace_id"`
	CategoryID  uuid.UUID        `json:"category_id"`
	AccountID   uuid.UUID        `json:"account_id"`
	HandledAt   pgtype.Timestamp `json:"handled_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}

type User struct {
	ID        uuid.UUID        `json:"id"`
	FirstName string           `json:"first_name"`
	LastName  string           `json:"last_name"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	Role      string           `json:"role"`
	LastLogin pgtype.Timestamp `json:"last_login"`
	Active    bool             `json:"active"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}

type Workspace struct {
	ID          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Currency    string           `json:"currency"`
	Language    string           `json:"language"`
	UserID      uuid.UUID        `json:"user_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}
